# -*- coding: utf-8 -*-
"""NLP_Berita.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGC5nDz4PVJ_wLleeltzUP6zIZvET5PV

# **TB2 Sesi 1 NLP**

## **Data Berita**
Membuat ringkasan dari berita tentang Covid 19 periode Januari 2021 (Detik.com dan Kompas.com)
"""

pip install newspaper3k

from newspaper import Article

article = Article('https://news.detik.com/berita-jawa-barat/d-5524450/3-pelajar-bogor-positif-corona-saat-uji-coba-sekolah-tatap-muka?_ga=2.121867979.1167836615.1617850834-1459962878.1617850834')

article2 = Article('https://nasional.kompas.com/read/2021/04/12/10380681/vaksin-sinovac-belum-ada-eul-dari-who-kemenkes-sebut-sudah-penuhi-kriteria')

article.download()
article.parse()

article2.download()
article2.parse()

print('Judul:', article.title)
print('Penulis:', article.authors)
print('Tanggal publikasi:', article.publish_date)
print('Teks berita:', article.text)
print('Gambar utama:', article.top_image)

print('Judul 2:', article2.title)
print('Penulis 2:', article2.authors)
print('Tanggal publikasi 2:', article2.publish_date)
print('Teks berita 2:', article2.text)
print('Gambar utama 2:', article2.top_image)

pip install nltk

import nltk
nltk.download('punkt')

article.nlp()
article2.nlp()

# To print out the full text
print(article.text)

# To print out the full text
print(article2.text)

article.keywords

article2.keywords

article.summary

article2.summary